# POSTGRESQL CONFIGURATION
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  ################################################################
  username: postgres
  host: localhost
  password: postgres

development:
  <<: *default
  database: personal_finance_development


test:
  <<: *default
  database: personal_finance_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV.fetch("DATABASE_HOST") { localhost } %>
    username: postgres
    password: postgres
  cache:
    <<: *primary_production
    database: personal_finance_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: personal_finance_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: personal_finance_production_cable
    migrations_paths: db/cable_migrate
